modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/J-Loongin/omniresonance/issues"

[[mods]]
modId="omniresonance"
version="${mod_version}"
displayName="Omni Resonance"
authors="loongin"
displayURL="https://github.com/J-Loongin/omniresonance"
logoFile="assets/omniresonance/textures/item/resonance_core.png"
logoBlur=true
description='''
Wireless cross-dimensional logistics.
'''

[[dependencies.omniresonance]]
modId="neoforge"
type="required"
versionRange="[21.1.248,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.omniresonance]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.omniresonance]]
modId="ae2"
type="optional"
versionRange="[19.2.17,20)"
ordering="AFTER"
side="BOTH"

[[dependencies.omniresonance]]
modId="mekanism"
type="optional"
versionRange="[10.7.19,11)"
ordering="AFTER"
side="BOTH"

[[dependencies.omniresonance]]
modId="ars_nouveau"
type="optional"
versionRange="[5.13.1,6)"
ordering="AFTER"
side="BOTH"

[[dependencies.omniresonance]]
modId="appmek"
type="optional"
versionRange="[1.6.3,1.7)"
ordering="AFTER"
side="BOTH"

[[dependencies.omniresonance]]
modId="industrialforegoingsouls"
type="optional"
versionRange="[1.10.7,1.11)"
ordering="AFTER"
side="BOTH"
